### ISSUE TITLE
Preloader Log shows Fatal error - some mods work, some not

### ISSUE THREAD

**Issue by Ioandar** [SubnauticaModding/QModManager#269]
**Describe the bug**
Preloader Log shows Fatal error - some mods work, some not

Map Mod works like before (including fog for unexplored areas)
Repair/charge in moonpool mod works like before
MoreShortCuts works fine

I tried different BepInEx but with no success. 
Out of ideas and help is highly welcome

Sorting-Folders does not work. (not yet investigated)

**Screenshots**

can not show what is not there 

**Additional info**
Preloader Log shows Fatal error...

`[Message:   BepInEx] BepInEx 5.4.19.0 - Subnautica (12.08.2020 09:09:33)
[Info   :   BepInEx] Running under Unity v2019.2.17.441
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.19.0]
[Info   :   BepInEx] Loaded 1 patcher method from [MirrorInternalLogs 9.0.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [QModManager.QModPluginGenerator 4.4.3.0]
[Info   :   BepInEx] Loaded 1 patcher method from [QModManager.UnityAudioFixer 4.3.0.0]
[Info   :   BepInEx] 4 patcher plugins loaded`

**Comment by desperationfighter** [comment]
You may want to join the Modding Discord.
Answers on Giuthub sometimes take a while.

However having a preloader file while running mods does not make sense.
Either QMM was able to start or not.
So the best would be to delete the preloader and qmodmanager Logfile. Restart the game once to regenerate them.
If Mods still don'T work we absolute need the FULL Logfile. Not parts of it or something..

**Comment by Ioandar** [comment]
I downloaded from nexus and maybe some mods are just too old...

QMM seems to work, since some mods work as described

How do I disable the "preloader"? I downloaded [this](https://www.nexusmods.com/subnautica/mods/201) and unzip it as explained on that page

Hope this is the full log?
https://pastebin.com/uy6ZmwDR

I am playing Subnautica again after a long time and the old install worked superfine!
Well, I will also check the discord you send.

any help getting [AutoSort](https://www.nexusmods.com/subnautica/mods/31) work again would be cool

**Comment by desperationfighter** [comment]
`I downloaded from nexus and maybe some mods are just too old...`
Most will work just fine. For sure there are execptions but AutoSortLockers work 100%

`How do I disable the "preloader"?`
You don't its a fallback Logfile if something heavenly failes and why you should anyway otherwise you would never know the Error? So this makes no sense. Or do i miss something ?

`Hope this is the full log?`
Your Logfile looks pretty confusing. It looks like its an very old QMM Version or something. 
Thats at least definitiv not what QMM would generate in the Latest version.

My best recommendation is:
Delete the "BepInEx" Folder + "winhttp.dll" + "doorstop_config.ini" from your GameFolder.
Reinstall QMM. Don't start the Game.
Follow additional this Steps
1- Delete ALL files in Subnautica_Data/Managed (or SubnauticaZero_Data/Managed)

2- Obtain those files again.
2.1- (Steam only) use Steam's File Integrity Check: https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335
2.2- (Epic Games only) use Epic's Verify process: https://cdn.discordapp.com/attachments/324210292194279424/769281527338106960/unknown.png

3- Then run the game again.

4- Go to Options -> check for a tab called "Mods". If it exists, then you're good to go.

5- (optional) If you had files in your game's root folder that were prefixed with "preloader_", you can safely remove them as they're no longer necessary.

If all this don't help. You should ask on the Help and Support Channel in the Modding Discord. May refer to here.
There are multiple people that can help going through everything possible.

`I am playing Subnautica again after a long time and the old install worked superfine!`
My Car worked when i buyed it 150.000KM earlier... Sorry the Sarcasm but for Real. The Game had multiple big updates in the last years that broke many Mods or even the Modloader itself and so on. But in the end it doesn't matter as long you now use the latest Version there should be no problems.

**Comment by Ioandar** [comment]
Thank you very much for taking the time to explain to me! 
I guess my old install somehow got mixed all up... I will do as you said and report the result. 
cheers

**Comment by Ioandar** [comment]
@desperationfighterm you sir are awesome! 

I followed all your steps and everything is working now!

ingame Mods-menu is different
All the mods are present
All the recipe show up
All the options also

Also the [logfile](https://pastebin.com/TRW8WebX) looks MUCH better now!

Thank you very very much! /salute
