### ISSUE TITLE
[Steam] QModManager 4.4.4 (& 4.4.4.1) are not loading on SBZ

### ISSUE THREAD

**Issue by VELD-Dev** [SubnauticaModding/QModManager#287]
I installed QMM 4.4.4, but the MM does not load, there's no mods tab, nor anything.  
It works only if I launch from the .exe, but of course, because I'm using Steam, the game closes and relaunches from Steam, and at this moment, when Steam runs the game, the QMM does not load.

I have no screenshot, but I know my installation is right, with QMM 4.4.3, it was running fine.

Version: **QModManager** 4.4.4 & **QModManager 4.4.4.1**
SBZ: **Steam** / Game Version: **Build of the October the 5th of 2022**

**Comment by toebeann** [comment]
This sounds more like an installation/troubleshooting issue rather than a bug with QMM itself.

I have just installed the latest version of BZ from Steam and the latest version of QMM for BZ and mod manager is showing up just fine, both in the stable branch and the experimental branch. The latest BZ steam build date for stable is 12th feb 2021, for experimental 5th dec 2022.

The best way to get help with these kinds of issues, whether they're bugs or not, is to [join the Subnautica Modding Discord](https://discord.gg/UpWuWwq), where we have two channels dedicated to help and support for troubleshooting issues such as these. You will likely get responses and a resolution quicker than you will here.

I advise bringing a copy of your `qmodmanager_log-SubnauticaZero.txt` file so that whoever responds to your query can take a look for causes of your error. Also, make sure you installed the release of QMM for BZ rather than for SN1, as this is a common cause of such issues.

Also, where did you get this QMM 4.4.4.1 from? As far as I am aware, no such version of QMM has been published either for SN1 or BZ.

**Comment by drnick88101** [comment]
I have the same issue with the original subnautica ever since the livin large update a few days ago.

**Comment by EldritchCarMaker** [comment]
As tobey said, the best way to get help is to join the modding discord (linked above) as we really can not easily help through here

**Comment by toebeann** [comment]
> I have the same issue with the original subnautica ever since the livin large update a few days ago.

![image](https://user-images.githubusercontent.com/45315526/207930506-51615474-63ee-4eba-87e6-1d788a479c94.png)

@drnick88101 Different issue.

**Comment by toebeann** [comment]
As there has been no further conversation on this issue in > 2 weeks, and this is believed to be an installation problem rather than a bug, I am closing this issue.
